server:
    port: 15007
spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            server:
                git:
                    password: ''
                    searchPaths: respo
                    uri: https://github.com/806330706/SpringcloudConfig
                    username: ''

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
