eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 15003
spring:
  application:
    name: service-feign
feign:
    httpclient:
        enabled: true
    hystrix:
      enabled: true